apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pinn-app
type: Opaque
data:
  root-user: YWRtaW4=  # admin
  root-password: YWRtaW4xMjM=  # admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: pinn-app
type: Opaque
data:
  password: MTIz  # 123