apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: pinn-app
data:
  ML_SERVICE_URL: "http://ml-service:8001"
  CLICKHOUSE_HOST: "clickhouse"
  CLICKHOUSE_PORT: "9000"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "admin123"
  MINIO_SECURE: "false"